apiVersion: v1
appVersion: 1.22-alpha.49b7997c687b7e0492c64311ea58df0064ba3d6c
description: Helm chart for istio ztunnel components
icon: https://istio.io/latest/favicons/android-192x192.png
keywords:
- istio-ztunnel
- istio
name: ztunnel
sources:
- https://github.com/istio/istio
version: 1.22-alpha.49b7997c687b7e0492c64311ea58df0064ba3d6c
